GET http://localhost:3001/products/Все/desc/1/
###

GET http://localhost:3001/search/123/asc/0
###

GET http://localhost:3001/orders/1278f727-7407-4548-ab72-25babe1c3e66
###

GET http://localhost:3001/order/b5b75841-0b44-4b71-a6a8-c8fdf57257b0
###

GET http://localhost:3001/categories
###
GET http://localhost:3001/productsAmount/Бункеры
###

POST http://localhost:3001/registerOrder
Content-Type: application/json

{
    "order": {
        "a": 3,
        "b": 4
    }
}
###

POST http://localhost:3001/register
Content-Type: application/json

{
    "name": "igor",
    "email": "w@w",
    "password": "w"
}
###

POST http://localhost:3001/login
Content-Type: application/json

{
    "email": "w@w",
    "password": "w"
}

###
