GET http://localhost:3001/users

###

POST http://localhost:3001/users
Content-Type: application/json

{
    "name": "hino",
    "password": "password"
}

###

POST http://localhost:3001/getOrders
Content-Type: application/json

{
    "userID": "6fc0cece-98a9-4f50-87d9-2ed738ae28a5"
}